version: "3"
services:
    nginx:
        container_name: account
        image: nginx:1.13
        hostname: account
        volumes:
            - ../www-data:/usr/share/nginx
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf
        links:
            - php71
        working_dir: /usr/share/nginx
    php71:
        container_name: account-php71
        image: php71:latest
        expose:
            - 9000
        volumes:
            - ../www-data:/usr/share/nginx
            - ./php.ini:/usr/local/etc/php/php.ini
        working_dir: /usr/share/nginx

networks:
    default:
        external:
            name: kong-net
